### PR TITLE
remove unneeded heights and reduce banner file size

### PR DESCRIPTION
**Pull request by stwa**
I wasn't able to remove the explicit max-height for .menu-wrapper, so I have increased the value to 25em to make sure there is no overflow. As it's the max-height property (and not real height) that shouldn't be a problem, the wrapper only grows to the size of its content. I removed some unneeded directives in the css which don't have any effect. Also I reduced the banner file size to ~217KB.

### CODE REVIEW

**Comment by clandmeter** [comment]
Nice. How did you get the image to be so much smaller?

Also, do we need to keep the other image? Maybe its an idea to include the original image in git for reference: https://unsplash.com/@roylandnye?photo=dfZbts6B4yw

**Comment by stwa** [comment]
You can use a random online image optimizer or something like
`convert -strip -quality 80 banner.jpg banner-min.jpg`

Yes, I kept the 'normal' image just for reference, we can save the original one instead.

**Comment by clandmeter** [comment]
Very weird, both menu's were on top on FF 47, but after I updated to FF 49 local menu is pushed down again. Looks like some regression in FF prior to v49.

Thanks, merging.

**Comment by clandmeter** [comment]
I just tried with a friends iphone SE and the background does not really scale very well (only shows the sky without mountains) . Maybe its related to the lower resolution of the SE. I wonder if we can fix that.

**Comment by jirutka** [comment]
I don’t think that’s a problem of lower resolution, the image scales well. I have 540 x 960 px and this is how it looks:

screenshot_2016-11-12-16-11-48

**Comment by jirutka** [comment]
BTW the banner picture looks horrible now, the compression is too damn high.

**Comment by clandmeter** [comment]
This is how it looks on an Iphone SE

img_2670

**Comment by stwa** [comment]
I also don’t think the position problem is because of image compression (resolution is the same). Also on my phone/laptop the image looks good and I don't have an iPhone to test :/
Should I upload the picture with less image compression to make sure it looks good on all devices?

**Comment by clandmeter** [comment]
I just compared them again and I don't see any difference ie:

https://raw.githubusercontent.com/alpinelinux/alpine-mksite/d046e07cf298a68871876b81a96297d13de2146b/_static/banner.jpg

vs

https://raw.githubusercontent.com/alpinelinux/alpine-mksite/master/_static/banner.jpg

@jirutka are you sure you see any compression changes?

**Comment by jirutka** [comment]
Yes, I do. 80% JPEG compression is too high, I usually don’t go below 90 % or 86 % if you really need very small size.

**Comment by stwa** [comment]
btw: compression of 90% still results in 316KB, which would be fairly acceptable

**Pull request merged**
